//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.WcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PathFault", Namespace="http://schemas.datacontract.org/2004/07/WcfServer")]
    [System.SerializableAttribute()]
    public partial class PathFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IPathService")]
    public interface IPathService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathService/GetPathInfo", ReplyAction="http://tempuri.org/IPathService/GetPathInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfClient.WcfService.PathFault), Action="http://tempuri.org/IPathService/GetPathInfoPathFaultFault", Name="PathFault", Namespace="http://schemas.datacontract.org/2004/07/WcfServer")]
        string[] GetPathInfo(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathService/GetPathInfo", ReplyAction="http://tempuri.org/IPathService/GetPathInfoResponse")]
        System.Threading.Tasks.Task<string[]> GetPathInfoAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPathServiceChannel : WcfClient.WcfService.IPathService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PathServiceClient : System.ServiceModel.ClientBase<WcfClient.WcfService.IPathService>, WcfClient.WcfService.IPathService {
        
        public PathServiceClient() {
        }
        
        public PathServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PathServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetPathInfo(string path) {
            return base.Channel.GetPathInfo(path);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPathInfoAsync(string path) {
            return base.Channel.GetPathInfoAsync(path);
        }
    }
}
